import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { api } from "../utils/api";

import "../styles/globals.css";
import Navbar from "../components/Navbar";
import Image from "next/image";
import Head from "next/head";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
          <>
      <Head>
        <title>Le fishe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-[#FAF9F6] p-2 flex h-[100px]">
        <Image alt="logo" className="absolute ml-auto mr-auto left-0 right-0" src="/fishlogo.png" width={100} height={100}></Image>
      </header>
      <main className="flex min-h-screen mt-[-100px] bg-[#FAF9F6]">
            <Navbar/>
            <Component {...pageProps} />
      </main>
    </>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
